name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build, run_release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Ubuntu texinfo bison flex
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install texinfo bison flex libgmp3-dev libmpfr-dev libmpc-dev
    
    - name: Install Mac texinfo bison flex
      if: matrix.os == 'macOS-latest'
      run: |
        brew update
        brew install texinfo bison flex gnu-sed gsl gmp mpfr

    - name: Runs all the stages in the shell
      run: |
        export PS2DEV=$PWD/ps2dev
        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
        export PATH=$PATH:$PS2DEV/ee/bin
        ./toolchain.sh

  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v2
        
    - name: Install MSYS2 texinfo bison flex
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: git msys2-devel base-devel binutils mingw-w64-i686-gcc binutils git unzip make texinfo tar patch mpc-devel p7zip man bison flex
        update: true
        shell: msys2 {0}

    - name: Runs all the stages in the shell
      run: |
        export PS2DEV=$PWD/ps2dev
        export PATH=$PATH:$PS2DEV/dvp/bin
        ./toolchain.sh
